### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by spkesDE** [spkesDE/com.spkes.vesync#1]
- [x] Offline Devices
- [x] Capability Checks inside api
- [x] Check Diagnostic Reports
- [x] Interval Check of devices
